#!/bin/bash

cat /dev/null | java -Xmx1G -XX:MaxPermSize=250m \
    -Dsbt.log.noformat=true \
    -Dbuild.number="$BUILD_NUMBER" \
    -Dbuild.vcs.number="$BUILD_VCS_NUMBER" \
    -Dhttp.proxyHost=devproxy.gul3.gnl \
    -Dhttp.proxyPort=3128 \
    -jar dev/sbt-launch-0.11.3-2.jar "$@"

